name: Publish Blog to Netlify

on:
  push:
    branches:
      - master

jobs:
  publish-netlify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         LICENSE_KEY: ${{secrets.LICENSE_KEY}}
        run: |
          cd ./build
          ./gradlewCustom --info --stacktrace
      - name: Publish
        uses: South-Paw/action-netlify-cli@1.0.1
        id: netlify
        with:
          args: 'deploy --json --prod --dir \"./site\" --message \"production [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.OXYGEN_XML_BLOG_NETLIFY }}
          NETLIFY_SITE_ID: ${{ secrets.OXYGEN_XML_BLOG_NETLIFY_SIDE_ID }} 
