name: Validate And Check For Completeness Blog

on:
  pull_request:
    branches: [ master ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate-check-completeness:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         SCRIPTING_LICENSE_KEY: ${{secrets.SCRIPTING_LICENSE_KEY}}
         BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          cd ./build
          ./gradlewCustom --build-file build-validate-check.gradle --info --stacktrace runValidation
          if test -f ../validationReport.md; then cat ../validationReport.md > $GITHUB_STEP_SUMMARY;exit 1; fi
